
version: "3.9"

services:
  postgres:
    image: postgres:17
    container_name: postgres-container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: data_kepegawaian
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - backend_network

  node-app:
    container_name: node-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    networks:
      - backend_network
    environment:
      NODE_ENV: development

volumes:
  postgres-data:

networks:
  backend_network:
